name: Docker Image CI

on:
  push:
    branches:
      - "main"
    paths:
      - "language-game/**"
  # pull_request:
  #   branches:
  #     - "main"
  #   paths:
  #     - "language-game/**"

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: fitamaksims/language-learning-game-server

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          # tags: ${{ steps.meta.outputs.tags }}
          tags: ${{ steps.meta.outputs.tags }}-${{ steps.vars.outputs.sha_short }}
          labels: ${{ steps.meta.outputs.labels }}
